-- ============================================
-- GROWTH KIT PHASES DATA
-- ============================================
-- This file contains the exact phase definitions for Growth Kit projects
-- as specified in the UX documentation.
--
-- These phases are automatically created when a Growth Kit project is initialized
-- via the initialize_growth_kit_project() function in schema.sql
--
-- This file is provided for reference and manual insertion if needed.
-- ============================================

-- Growth Kit Phase Definitions
-- Each project gets exactly 4 phases when initialized

-- Phase 1: Strategy locked in (Days 0–2)
-- Subtitle: "Offer, goal and funnel map agreed."
-- Checklist items:
--   - Onboarding complete
--   - Strategy / funnel call done
--   - Main offer + 90 day goal confirmed
--   - Simple funnel map agreed

-- Phase 2: Copy & email engine (Days 3–5)
-- Subtitle: "We write your site copy and 5 emails."
-- Checklist items:
--   - Draft website copy ready
--   - Draft 5-email nurture sequence ready
--   - You reviewed and approved copy
--   - Any changes locked in
-- Links:
--   - View website copy
--   - View email sequence

-- Phase 3: Build the funnel (Days 6–10)
-- Subtitle: "Pages, lead magnet and blog hub built."
-- Checklist items:
--   - 4–6 page site built on staging
--   - Lead magnet page + thank you page built
--   - Opt-in forms wired to your email platform
--   - Blog hub and 1–2 starter posts set up
--   - Staging link shared
-- Links:
--   - View staging funnel

-- Phase 4: Test, launch & handover (Days 11–14)
-- Subtitle: "We test the full journey and go live."
-- Checklist items:
--   - Funnel tested from first visit to booked call
--   - Domain connected
--   - Tracking checked (Analytics / pixels)
--   - 5-email sequence switched on
--   - Loom walkthrough recorded and shared
-- Links:
--   - View live funnel
--   - Watch Loom walkthrough

-- ============================================
-- EXAMPLE: Manual Insertion (for reference)
-- ============================================
-- To manually insert phases for a Growth Kit project, use this pattern:
--
-- DECLARE
--   v_project_id UUID := 'your-project-id-here';
--   v_phase_1_id UUID;
--   v_phase_2_id UUID;
--   v_phase_3_id UUID;
--   v_phase_4_id UUID;
-- BEGIN
--   -- Insert Phase 1
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 1, 'PHASE_1', 'Strategy locked in', 'Offer, goal and funnel map agreed.', 'Days 0-2', 'NOT_STARTED')
--   RETURNING id INTO v_phase_1_id;
--   
--   -- Insert Phase 2
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 2, 'PHASE_2', 'Copy & email engine', 'We write your site copy and 5 emails.', 'Days 3-5', 'NOT_STARTED')
--   RETURNING id INTO v_phase_2_id;
--   
--   -- Insert Phase 3
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 3, 'PHASE_3', 'Build the funnel', 'Pages, lead magnet and blog hub built.', 'Days 6-10', 'NOT_STARTED')
--   RETURNING id INTO v_phase_3_id;
--   
--   -- Insert Phase 4
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 4, 'PHASE_4', 'Test, launch & handover', 'We test the full journey and go live.', 'Days 11-14', 'NOT_STARTED')
--   RETURNING id INTO v_phase_4_id;
--   
--   -- Insert checklist items for Phase 1
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_1_id, 'Onboarding complete', 1, false),
--     (v_phase_1_id, 'Strategy / funnel call done', 2, false),
--     (v_phase_1_id, 'Main offer + 90 day goal confirmed', 3, false),
--     (v_phase_1_id, 'Simple funnel map agreed', 4, false);
--   
--   -- Insert checklist items for Phase 2
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_2_id, 'Draft website copy ready', 1, false),
--     (v_phase_2_id, 'Draft 5-email nurture sequence ready', 2, false),
--     (v_phase_2_id, 'You reviewed and approved copy', 3, false),
--     (v_phase_2_id, 'Any changes locked in', 4, false);
--   
--   -- Insert checklist items for Phase 3
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_3_id, '4-6 page site built on staging', 1, false),
--     (v_phase_3_id, 'Lead magnet page + thank you page built', 2, false),
--     (v_phase_3_id, 'Opt-in forms wired to your email platform', 3, false),
--     (v_phase_3_id, 'Blog hub and 1-2 starter posts set up', 4, false),
--     (v_phase_3_id, 'Staging link shared', 5, false);
--   
--   -- Insert checklist items for Phase 4
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_4_id, 'Funnel tested from first visit to booked call', 1, false),
--     (v_phase_4_id, 'Domain connected', 2, false),
--     (v_phase_4_id, 'Tracking checked (Analytics / pixels)', 3, false),
--     (v_phase_4_id, '5-email sequence switched on', 4, false),
--     (v_phase_4_id, 'Loom walkthrough recorded and shared', 5, false);
-- END;

-- ============================================
-- PHASE DATA SUMMARY
-- ============================================

-- Growth Kit Phase 1: Strategy locked in
--   - Days: 0-2
--   - Subtitle: "Offer, goal and funnel map agreed."
--   - Checklist: 4 items

-- Growth Kit Phase 2: Copy & email engine
--   - Days: 3-5
--   - Subtitle: "We write your site copy and 5 emails."
--   - Checklist: 4 items
--   - Links: View website copy, View email sequence

-- Growth Kit Phase 3: Build the funnel
--   - Days: 6-10
--   - Subtitle: "Pages, lead magnet and blog hub built."
--   - Checklist: 5 items
--   - Links: View staging funnel

-- Growth Kit Phase 4: Test, launch & handover
--   - Days: 11-14
--   - Subtitle: "We test the full journey and go live."
--   - Checklist: 5 items
--   - Links: View live funnel, Watch Loom walkthrough

-- ============================================
-- NOTES
-- ============================================
-- - All phases start with status 'NOT_STARTED'
-- - Phase status is automatically updated by triggers in phases_triggers.sql
--   based on checklist item completion
-- - Phase links are stored in the phase_links table (defined in schema.sql)
-- - The initialize_growth_kit_project() function in schema.sql automatically
--   creates these phases and checklist items when a new Growth Kit project is created

