-- ============================================
-- LAUNCH KIT PHASES DATA
-- ============================================
-- This file contains the exact phase definitions for Launch Kit projects
-- as specified in the UX documentation (Final Clean Version).
--
-- These phases are automatically created when a Launch Kit project is initialized
-- via the initialize_launch_kit_project() function in schema.sql
--
-- This file is provided for reference and manual insertion if needed.
-- ============================================

-- Launch Kit Phase Definitions
-- Each project gets exactly 4 phases when initialized

-- Phase 1: Inputs & clarity (Days 0–2)
-- Subtitle: "Lock the message and plan."
-- Checklist items:
--   1. Onboarding steps completed
--   2. Brand / strategy call completed
--   3. Simple 14 day plan agreed
-- Next from us (examples):
--   - "We are taking your inputs and call notes and shaping the outline for your 3 pages."
-- Next from you (examples):
--   - "Nothing for now. We will come back to you with copy to review."

-- Phase 2: Words that sell (Days 3–5)
-- Subtitle: "We write your 3 pages."
-- Checklist items:
--   1. Draft homepage copy ready
--   2. Draft offer / services page ready
--   3. Draft contact/about copy ready
--   4. You reviewed and approved copy
-- Links (optional):
--   - View copy doc
-- Next from us (examples):
--   - "We are drafting your homepage and offer page copy."
-- Next from you (examples):
--   - "Please review your copy and leave one round of comments."

-- Phase 3: Design & build (Days 6–10)
-- Subtitle: "We turn copy into a 3 page site."
-- Checklist items:
--   1. Site layout built for all 3 pages
--   2. Mobile checks done
--   3. Testimonials and proof added
--   4. Staging link shared with you
-- Links (optional):
--   - View staging site
-- Next from us:
--   - "We are building your 3 page site using your approved copy."
-- Next from you:
--   - "Please click through the staging site and flag any small tweaks."

-- Phase 4: Test & launch (Days 11–14)
-- Subtitle: "We connect domain, test and go live."
-- Checklist items:
--   1. Forms tested
--   2. Domain connected
--   3. Final tweaks applied
--   4. Loom walkthrough recorded and shared
-- Links (optional):
--   - View live site
--   - Watch Loom walkthrough
-- Next from us:
--   - "We are testing your contact form and connecting your domain."
-- Next from you:
--   - "Please confirm everything looks good and share any final non-urgent tweaks."

-- ============================================
-- EXAMPLE: Manual Insertion (for reference)
-- ============================================
-- To manually insert phases for a Launch Kit project, use this pattern:
--
-- DECLARE
--   v_project_id UUID := 'your-project-id-here';
--   v_phase_1_id UUID;
--   v_phase_2_id UUID;
--   v_phase_3_id UUID;
--   v_phase_4_id UUID;
-- BEGIN
--   -- Insert Phase 1
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 1, 'PHASE_1', 'Inputs & clarity', 'Lock the message and plan.', 'Days 0-2', 'NOT_STARTED')
--   RETURNING id INTO v_phase_1_id;
--   
--   -- Insert Phase 2
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 2, 'PHASE_2', 'Words that sell', 'We write your 3 pages.', 'Days 3-5', 'NOT_STARTED')
--   RETURNING id INTO v_phase_2_id;
--   
--   -- Insert Phase 3
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 3, 'PHASE_3', 'Design & build', 'We turn copy into a 3 page site.', 'Days 6-10', 'NOT_STARTED')
--   RETURNING id INTO v_phase_3_id;
--   
--   -- Insert Phase 4
--   INSERT INTO phases (project_id, phase_number, phase_id, title, subtitle, day_range, status)
--   VALUES
--     (v_project_id, 4, 'PHASE_4', 'Test & launch', 'We connect domain, test and go live.', 'Days 11-14', 'NOT_STARTED')
--   RETURNING id INTO v_phase_4_id;
--   
--   -- Insert checklist items for Phase 1
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_1_id, 'Onboarding steps completed', 1, false),
--     (v_phase_1_id, 'Brand / strategy call completed', 2, false),
--     (v_phase_1_id, 'Simple 14 day plan agreed', 3, false);
--   
--   -- Insert checklist items for Phase 2
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_2_id, 'Draft homepage copy ready', 1, false),
--     (v_phase_2_id, 'Draft offer / services page ready', 2, false),
--     (v_phase_2_id, 'Draft contact/about copy ready', 3, false),
--     (v_phase_2_id, 'You reviewed and approved copy', 4, false);
--   
--   -- Insert checklist items for Phase 3
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_3_id, 'Site layout built for all 3 pages', 1, false),
--     (v_phase_3_id, 'Mobile checks done', 2, false),
--     (v_phase_3_id, 'Testimonials and proof added', 3, false),
--     (v_phase_3_id, 'Staging link shared with you', 4, false);
--   
--   -- Insert checklist items for Phase 4
--   INSERT INTO checklist_items (phase_id, label, sort_order, is_done)
--   VALUES
--     (v_phase_4_id, 'Forms tested', 1, false),
--     (v_phase_4_id, 'Domain connected', 2, false),
--     (v_phase_4_id, 'Final tweaks applied', 3, false),
--     (v_phase_4_id, 'Loom walkthrough recorded and shared', 4, false);
--   
--   -- Optional: Insert phase links
--   -- Phase 2: View copy doc
--   -- INSERT INTO phase_links (phase_id, label, url, sort_order)
--   -- VALUES (v_phase_2_id, 'View copy doc', 'https://...', 1);
--   
--   -- Phase 3: View staging site
--   -- INSERT INTO phase_links (phase_id, label, url, sort_order)
--   -- VALUES (v_phase_3_id, 'View staging site', 'https://...', 1);
--   
--   -- Phase 4: View live site, Watch Loom walkthrough
--   -- INSERT INTO phase_links (phase_id, label, url, sort_order)
--   -- VALUES 
--   --   (v_phase_4_id, 'View live site', 'https://...', 1),
--   --   (v_phase_4_id, 'Watch Loom walkthrough', 'https://...', 2);
-- END;

-- ============================================
-- PHASE DATA SUMMARY
-- ============================================

-- Launch Kit Phase 1: Inputs & clarity
--   - Days: 0-2
--   - Subtitle: "Lock the message and plan."
--   - Checklist: 3 items
--   - No links

-- Launch Kit Phase 2: Words that sell
--   - Days: 3-5
--   - Subtitle: "We write your 3 pages."
--   - Checklist: 4 items
--   - Links: View copy doc (optional)

-- Launch Kit Phase 3: Design & build
--   - Days: 6-10
--   - Subtitle: "We turn copy into a 3 page site."
--   - Checklist: 4 items
--   - Links: View staging site (optional)

-- Launch Kit Phase 4: Test & launch
--   - Days: 11-14
--   - Subtitle: "We connect domain, test and go live."
--   - Checklist: 4 items
--   - Links: View live site, Watch Loom walkthrough (optional)

-- ============================================
-- NOTES
-- ============================================
-- - All phases start with status 'NOT_STARTED'
-- - Phase status is automatically updated by triggers in phases_triggers.sql
--   based on checklist item completion
-- - Phase links are stored in the phase_links table (defined in schema.sql)
--   and are optional - they can be added later by admins
-- - "Next from us" and "Next from you" text is stored at the project level
--   in the projects table (next_from_us, next_from_you columns)
-- - The initialize_launch_kit_project() function in schema.sql automatically
--   creates these phases and checklist items when a new Launch Kit project is created

